# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: normalized_event.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16normalized_event.proto\x12\x11tinvest.signal.v1\"\xfb\x01\n\x11NormalizedEventV1\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x15\n\rinstrument_id\x18\x03 \x01(\t\x12\x0e\n\x06ticker\x18\x04 \x01(\t\x12\x12\n\nclass_code\x18\x05 \x01(\t\x12\r\n\x05\x61lias\x18\x06 \x01(\t\x12\x0c\n\x04\x66igi\x18\x07 \x01(\t\x12\x0b\n\x03uid\x18\x08 \x01(\t\x12\x0b\n\x03lot\x18\t \x01(\x05\x12\x1b\n\x13source_time_rfc3339\x18\n \x01(\t\x12\x1b\n\x13received_at_rfc3339\x18\x0b \x01(\t\x12\x14\n\x0cpayload_json\x18\x0c \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'normalized_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NORMALIZEDEVENTV1']._serialized_start=46
  _globals['_NORMALIZEDEVENTV1']._serialized_end=297
# @@protoc_insertion_point(module_scope)
