# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trigger_signal.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'trigger_signal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14trigger_signal.proto\x12\x11tinvest.signal.v1\"\xcb\x02\n\x0fTriggerSignalV1\x12\x11\n\tsignal_id\x18\x01 \x01(\t\x12\x1b\n\x13\x64\x65tected_at_rfc3339\x18\x02 \x01(\t\x12\x15\n\rinstrument_id\x18\x03 \x01(\t\x12\x0e\n\x06ticker\x18\x04 \x01(\t\x12\x12\n\nclass_code\x18\x05 \x01(\t\x12\r\n\x05\x61lias\x18\x06 \x01(\t\x12\x19\n\x11source_event_type\x18\x07 \x01(\t\x12\x13\n\x0bsignal_type\x18\x08 \x01(\t\x12\x10\n\x08severity\x18\t \x01(\x05\x12\x14\n\x0cmetric_value\x18\n \x01(\x01\x12\x16\n\x0e\x62\x61seline_value\x18\x0b \x01(\x01\x12\x0f\n\x07z_score\x18\x0c \x01(\x01\x12\x16\n\x0ewindow_seconds\x18\r \x01(\x05\x12\x0f\n\x07summary\x18\x0e \x01(\t\x12\x14\n\x0cpayload_json\x18\x0f \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trigger_signal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRIGGERSIGNALV1']._serialized_start=44
  _globals['_TRIGGERSIGNALV1']._serialized_end=375
# @@protoc_insertion_point(module_scope)
