# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trigger_signal.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14trigger_signal.proto\x12\x11tinvest.signal.v1"\xc2\x04\n\x0fTriggerSignalV1\x12\x11\n\tsignal_id\x18\x01 \x01(\t\x12\x1b\n\x13detected_at_rfc3339\x18\x02 \x01(\t\x12\x15\n\rinstrument_id\x18\x03 \x01(\t\x12\x0e\n\x06ticker\x18\x04 \x01(\t\x12\x12\n\nclass_code\x18\x05 \x01(\t\x12\r\n\x05alias\x18\x06 \x01(\t\x12\x19\n\x11source_event_type\x18\x07 \x01(\t\x12\x13\n\x0bsignal_type\x18\x08 \x01(\t\x12\x10\n\x08severity\x18\t \x01(\x05\x12\x14\n\x0cmetric_value\x18\n \x01(\x01\x12\x16\n\x0ebaseline_value\x18\x0b \x01(\x01\x12\x0f\n\x07z_score\x18\x0c \x01(\x01\x12\x16\n\x0ewindow_seconds\x18\r \x01(\x05\x12\x0f\n\x07summary\x18\x0e \x01(\t\x12\x14\n\x0cpayload_json\x18\x0f \x01(\t\x12\x17\n\x0fsource_event_id\x18\x10 \x01(\t\x12\x1f\n\x17source_event_at_rfc3339\x18\x11 \x01(\t\x12\x1d\n\x15signal_schema_version\x18\x12 \x01(\t\x12#\n\x1bexpectation_catalog_version\x18\x13 \x01(\t\x12\x1f\n\x17detector_config_version\x18\x14 \x01(\t\x12\x1f\n\x17delivery_config_version\x18\x15 \x01(\t\x12\x1a\n\x12cost_model_version\x18\x16 \x01(\t\x12\x19\n\x11provenance_status\x18\x17 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR,
    "trigger_signal_pb2",
    _globals,
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TRIGGERSIGNALV1"]._serialized_start = 44
    _globals["_TRIGGERSIGNALV1"]._serialized_end = 630
# @@protoc_insertion_point(module_scope)
